name: Notification Google Chat

on: 
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Envoyer une notification Google Chat
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: "TicTacToe"
        url: "https://chat.googleapis.com/v1/spaces/XXXXX/messages?key=XXXX&token=XXXX"
        status: ${{ job.status }}
      if: always()
